#python3 SVM.py & 
#python3 SVM.py id &
#python3 SVM.py proto &
#python3 SVM.py service &
#python3 SVM.py state &
#python3 SVM.py spkts &
#python3 SVM.py dpkts &
#python3 SVM.py sbytes &
#python3 SVM.py dbytes &
#python3 SVM.py rate &
#python3 SVM.py sttl &
#python3 SVM.py dttl &
#python3 SVM.py sload &
#python3 SVM.py dload &
#python3 SVM.py sloss &
#python3 SVM.py dloss &
#python3 SVM.py sinpkt &
#python3 SVM.py dinpkt &
python3 SVM.py sjit &
#python3 SVM.py djit &
#python3 SVM.py swin &
#python3 SVM.py stcpb &
#python3 SVM.py dtcpb &
#python3 SVM.py dwin &
#python3 SVM.py tcprtt &
#python3 SVM.py synack &
#python3 SVM.py ackdat &
#python3 SVM.py smean &
#python3 SVM.py dmsean &
#python3 SVM.py trans_depth &
#python3 SVM.py response_body_len &
python3 SVM.py ct_srv_src &
#python3 SVM.py ct_state_ttl &
#python3 SVM.py ct_dst_ltm &
python3 SVM.py ct_src_dport_ltm &
#python3 SVM.py ct_dst_sport_ltm &
#python3 SVM.py ct_dst_src_ltm &
#python3 SVM.py is_ftp_login &
#python3 SVM.py ct_ftp_cmd &
#python3 SVM.py ct_flw_http_mthd &
#python3 SVM.py ct_src_ltm &
#python3 SVM.py ct_srv_dst &
#python3 SVM.py is_sm_ips_ports &
python3 SVM.py label &